services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    ports:
      - "8081:8080"
    environment:
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_USER: "fzsgball"
      DB_PASS: "123456"
      DB_NAME: "official_book_library"
    depends_on:
      - db 

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    ports:
      - "8088:80"
    depends_on:
      - backend

  db:
    image: mariadb:10.5
    container_name: db
    environment:
      MARIADB_ROOT_PASSWORD: "root_password_for_testing"
      MARIADB_USER: "fzsgball"
      MARIADB_PASSWORD: "123456" 
      MARIADB_DATABASE: "official_book_library"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

networks:
  default:
    driver: bridge

volumes:
  db_data: